// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OwnedTypeDetached.Db;

namespace OwnedTypeDetached.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200619130544_InitTestDb3")]
    partial class InitTestDb3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OwnedTypeDetached.Entities.TokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Test","Test");
                });

            modelBuilder.Entity("OwnedTypeDetached.Entities.TokenEntity", b =>
                {
                    b.OwnsOne("OwnedTypeDetached.Entities.Extension", "Extension", b1 =>
                        {
                            b1.Property<int>("TokenEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<DateTime?>("CreateDate")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<int?>("EntityState")
                                .HasColumnType("integer");

                            b1.Property<bool?>("IsDelete")
                                .HasColumnType("boolean");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("timestamp without time zone");

                            b1.HasKey("TokenEntityId");

                            b1.ToTable("Test");

                            b1.WithOwner()
                                .HasForeignKey("TokenEntityId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
